### ISSUE TITLE
Strict variable checking

### ISSUE THREAD

**Issue by mobileoverlord** [fhunleth/fwup#65]
While updating an fwup.conf file I was renaming variables and missed some. When it tried to execute complete task, it failed with misleading error messages. Fwup should warn / error on unset variables.

**Comment by fhunleth** [comment]
Fwup can't warn on unset variables, or at least I'm pretty sure that it can't, since the variable lookup is done by libconfuse. Fwup can detect empty strings for parameters, though, and I think that will catch what happened to you. I thought that I handled this case, but it turned out that if you had a variable as a parameter and it was undefined that an empty string was passed. `strtoull` happily returned 0 instead of reporting an error. I added a check to fail on empty strings. The error message is not as helpful as it could be, but you'll get an invalid argument error with the right line number. That should be a big improvement over succeeding and accidentally overwriting your MBR or whatever is at offset 0.

The fix is in 485befd21eb3381e3f8ebd5cefe0252834203352.
